-- ═══════════════════════════════════════════════════════════════════
-- TABLE CLIENTS — OptiTechX / Defiligne
-- Base clients à facturer — à exécuter dans Supabase SQL Editor
-- Généré le 2026-08-17  |  256 clients
-- ═══════════════════════════════════════════════════════════════════

-- ── 1. Création de la table ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.clients (
  id                BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  nom               TEXT NOT NULL UNIQUE,
  adresse_site      TEXT,
  adresse_siege     TEXT,
  commercial        TEXT,
  email_facturation TEXT,
  telephone         TEXT,
  siret             TEXT,
  tva_intracom      TEXT,
  tarif_contrat     DECIMAL(8,2),
  type_contrat      TEXT DEFAULT 'ponctuel',
  notes_facturation TEXT,
  actif             BOOLEAN DEFAULT TRUE,
  notion_id         TEXT,
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP DEFAULT NOW()
);

-- ── 2. Index ─────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_clients_nom        ON public.clients (nom);
CREATE INDEX IF NOT EXISTS idx_clients_commercial ON public.clients (commercial);
CREATE INDEX IF NOT EXISTS idx_clients_actif      ON public.clients (actif);

-- ── 3. Trigger updated_at ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_clients_updated_at ON public.clients;
CREATE TRIGGER trg_clients_updated_at
  BEFORE UPDATE ON public.clients
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── 4. RLS ───────────────────────────────────────────────────────────
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "clients_select" ON public.clients
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "clients_insert" ON public.clients
  FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "clients_update" ON public.clients
  FOR UPDATE USING (auth.role() = 'service_role');

-- ── 5. Realtime ──────────────────────────────────────────────────────
ALTER PUBLICATION supabase_realtime ADD TABLE public.clients;

-- ── 6. INSERT — 256 clients ──────────────────────────────────────────
INSERT INTO public.clients (nom, adresse_site, adresse_siege, commercial)
VALUES
  (E'(BELLIN TP)', E'Rue du Petit Nieul 86360 Montamise', NULL, E'Cindy HERBET'),
  (E'(CHANEL SAM)', E'One pl monte Carlo 98000 Monaco', NULL, E'Johann Monlouis'),
  (E'(COMMINGES METAUX SERVICES)', NULL, NULL, E'Johann Monlouis'),
  (E'(DAIS / ADSEA 77)', E'509 rue Gauton Biron 77190 DAMMARIE LES LYS', E'Chemin du Coudray Menereaux 77950 Maincy', E'Cindy HERBET'),
  (E'(JARDIREVE DEOLS - VILLAVERDE DEOLS)', NULL, NULL, E'Johann Monlouis'),
  (E'(JARLISE - HOTEL PAVILLON BLEU)', NULL, NULL, E'Cindy HERBET'),
  (E'(LE CAMPUS)', NULL, NULL, E'Cindy HERBET'),
  (E'(RICHARD FRERES)', NULL, NULL, E'Johann Monlouis'),
  (E'(ROY SA)', NULL, NULL, E'Johann Monlouis'),
  (E'(World Medical association)', NULL, NULL, E'Johann Monlouis'),
  (E'15 NANCY- HOTEL LE GRAND QUARTIER', NULL, NULL, E'Cindy HERBET'),
  (E'34 SNA-N - DIRECTION GÉNÉRALE DE L''''AVIATION CIVILE', E'Tour de contrôle , allée Royale Air force 62520 LE TOUQUET', NULL, E'Johann Monlouis'),
  (E'911 (MEDISAFE)', NULL, NULL, E'Cindy HERBET'),
  (E'ABSCIS BERTIN CONSTRUCTION', E'21 Avenue de la grande plaine 14760 BretteVille sur Odon', E'21 Avenue de la Grande Plaine 14760 BRETTEVILLE SUR ODON', E'Cindy HERBET'),
  (E'ADAMAS - IXINA MENNEVAL', NULL, NULL, E'Cindy HERBET'),
  (E'ADAPEI 64 - RESIDENCE LE CLOS FLEURI', NULL, NULL, E'Johann Monlouis'),
  (E'ADSEA 77', E'372 avenue générale leclerc 77000 Melun', NULL, E'Cindy HERBET'),
  (E'ADVANCE - IXINA GUICHAINVILLE', NULL, NULL, E'Cindy HERBET'),
  (E'AGATHEA - VILLAVERDE MONTPELLIER - LE CRÈS', NULL, NULL, E'Johann Monlouis'),
  (E'AGOSPAP', NULL, NULL, E'Cindy HERBET'),
  (E'AGRI MELESSE - BRICOPRO MELESSE', NULL, NULL, E'Johann Monlouis'),
  (E'AGRI NORD 44', NULL, NULL, E'Johann Monlouis'),
  (E'AGRI PIECES 88', NULL, NULL, E'Johann Monlouis'),
  (E'AGY LIN SOCIETE COOPERATIVE AGRICOLE', E'555 Rue de la Veslière 76110 Goderville', NULL, E'Cindy HERBET'),
  (E'AIRBUS FLIGHT ACADEMY EUROPE', E'Chemin de saint jean BA 701 13661 Salon Air', NULL, E'Johann Monlouis'),
  (E'AJIMATERIEL', NULL, NULL, E'Johann Monlouis'),
  (E'AKINAS - CUISINES RÉFÉRENCES PONT AUDEMER', NULL, NULL, E'Cindy HERBET'),
  (E'Alfa diffusion', E'167-169 Quai de la bataille de Stalingrad 92130 Issy-les-Moulineaux', NULL, E'Cindy HERBET'),
  (E'AMF ACHAT METAUX FERRAILLES', NULL, NULL, E'Cindy HERBET'),
  (E'ANIMALIS', E'98 avenue du grand sud 37170 Chambray les tours', NULL, E'Cindy HERBET'),
  (E'APC 58 - NIEVRE PROTECTION CIVILE', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'ARAMIS - CUISINE PLUS BUCHELAY', NULL, NULL, E'Cindy HERBET'),
  (E'ARBOISIE OPCO - HOTEL ARBOISIE MEGEVE', NULL, NULL, E'Johann Monlouis'),
  (E'ARENAS - IXINA BOULOGNE BILLANCOURT', NULL, NULL, E'Cindy HERBET'),
  (E'ARTEMIS - IXINA BUCHELAY', NULL, NULL, E'Cindy HERBET'),
  (E'ATELIER INTERIOR SA', NULL, NULL, E'Cindy HERBET'),
  (E'BATIFER', E'19 rue de kingersheim 68120 Richwiller', NULL, E'Johann Monlouis'),
  (E'BATIGERE EN ILE DE FRANCE', E'17 Rue Victor Hugo 91290 Arpajon', NULL, E'Cindy HERBET'),
  (E'BERSHKA FRANCE', E'11 rue de bordeaux 37000 Tours', NULL, E'Cindy HERBET'),
  (E'BIG MAT NOEL MATERIAUX', E'Espace Driant rue saint Michel 55100 Verdun', NULL, E'Johann Monlouis'),
  (E'BOITEL ET FILS', NULL, NULL, E'Cindy HERBET'),
  (E'Bowling de Chartres', NULL, NULL, E'Johann Monlouis'),
  (E'BOYER', E'35 rue de la république 94370 Sucy en Brie', NULL, E'Cindy HERBET'),
  (E'BRANT''HOME LOISIRS - O''BRICO', NULL, NULL, E'Johann Monlouis'),
  (E'BRICO THENON - BRICO PRO', NULL, NULL, E'Johann Monlouis'),
  (E'BRICO TRAVO', NULL, NULL, E'Johann Monlouis'),
  (E'CAISSE REGIONALE ASSURANCE MALADIE (CRAMIF)', E'17-19 place de l''''argonne 75019 Paris', NULL, E'Cindy HERBET'),
  (E'Camping Les Pins bleu', NULL, NULL, E'Johann Monlouis'),
  (E'CARGLASS SERVICES', E'7 Avenue de la Patelle 95310 Saint-Ouen-l''Aumône', NULL, E'Cindy HERBET'),
  (E'CERA', NULL, NULL, E'Cindy HERBET'),
  (E'CFPTS', NULL, NULL, E'Cindy HERBET'),
  (E'CHANEL', E'40 rue delizy 93694 Pantin', NULL, E'Cindy HERBET'),
  (E'CHANEL COORDINATION', E'Rue Haie Marteau 95470 Vemars', NULL, E'Cindy HERBET'),
  (E'CHANEL PARFUMS BEAUTE', E'4 rue du bois barbier 60880 Le Meux', NULL, E'Cindy HERBET'),
  (E'CITY FUN - LECLERC-HORTALA', NULL, NULL, E'Johann Monlouis'),
  (E'CLAAS RESEAU AGRICOLE', E'Camp de la vabre 30730 Gajan', NULL, E'Johann Monlouis'),
  (E'CLUB ALPIN FRANCAIS DE BORDEAUX', E'50 avenue Georges clemenceau 33400 TALENCE', NULL, E'Priscilla BEUZELIN'),
  (E'COMITE ETUDES SOINS AUX POLYHANDICAPES - EEAP LES HEURES C', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'COMMUNAUTE COMMUNE VEXIN VAL DE SEINE (CCVVS)', E'2 chemin  de l''''Aubette 95450 Bray et lu', NULL, E'Cindy HERBET'),
  (E'COMMUNAUTE DE COMMUNES DE BRUYERES - VALLONS DES VOSGES', E'4 rue de la 36 eme division u.s 88600 bruyères', NULL, E'Cindy HERBET'),
  (E'COMMUNAUTE DE COMMUNES DU PAYS HOUDANAIS (CCPH)', E'Chemin de ronde 78550 Houdan', NULL, E'Cindy HERBET'),
  (E'COMMUNE D AUJARGUES', NULL, NULL, E'Johann Monlouis'),
  (E'COMMUNE DE BONDY', E'5 allée becquerel 93140 Bondy', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE BRUYERES', E'3 rue léopold 88600 Bruyères', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE BUCHELAY', E'18 rue pasteur 78200 Buchelay', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE CHAVANGES', NULL, NULL, E'Johann Monlouis'),
  (E'COMMUNE DE COMPIEGNE', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'COMMUNE DE FOLLAINVILLE-DENNEMON', E'5 rue des coteaux du vexin 78520 Follainville dennemont', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE GOMMECOURT', E'18 Rue Robert Mennessier 78270 Gommecourt', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE LIMETZ VILLEZ', E'4 rue de la mairie 78270 Limetz-Villez', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE LUNEL', E'240 rue Mario roustan 34400 Lunel', NULL, E'Johann Monlouis'),
  (E'COMMUNE DE MAGNANVILLE', E'3 Rue François Franque 78200 Magnanville', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE MANTES LA JOLIE', E'31 rue Gambetta 78200 MANTES LA JOLIE', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE NAVEIL', NULL, NULL, E'Johann Monlouis'),
  (E'COMMUNE DE PONT SUR VANNE', E'1 Bis Grande Rue 89190 Pont-sur-Vanne', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE PONTOISE', E'Place de la Fraternité 95300 Pontoise', E'30 Bis Les Hauts de Marcouville 95300 Pontoise', E'Cindy HERBET'),
  (E'COMMUNE DE SAINT MARTIN D''URIAGE', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'COMMUNE DE SAINT MICHEL DE VAX', NULL, NULL, E'Johann Monlouis'),
  (E'COMMUNE DE SAINTE FAUSTE', NULL, NULL, E'Cindy HERBET'),
  (E'Commune de Sorbiers', NULL, NULL, E'Johann Monlouis'),
  (E'COMMUNE DE TRAPPES', E'1 rue de l''''abreuvoir 78190 Trappes', NULL, E'Cindy HERBET'),
  (E'COMMUNE DE VAUX LE PENIL', E'4 place beuve et gantier 77000 Vaux-le-Pénil', NULL, E'Cindy HERBET'),
  (E'COMMUNE D''ECQUEVILLY', E'1Ter Place Henri Deutsch de Meurthe 78920 Ecquevilly', NULL, E'Cindy HERBET'),
  (E'COMMUNE NEUVY PAILLOUX', NULL, NULL, E'Cindy HERBET'),
  (E'COMPTOIR DE PROMOTION DU VERRE (COPROVER)', NULL, NULL, E'Johann Monlouis'),
  (E'COTE JARDIN', NULL, NULL, E'Cindy HERBET'),
  (E'CREATIONS FUSALP', E'9 Rue Alphonse de Neuville 75017 Paris', NULL, E'Cindy HERBET'),
  (E'CREATIS', E'14 bd haussmann 75009 Paris', NULL, E'Cindy HERBET'),
  (E'CUISINE PLUS FRANCE', NULL, NULL, E'Cindy HERBET'),
  (E'DECALA Studio Giverny', NULL, NULL, E'Johann Monlouis'),
  (E'DECLIC', NULL, NULL, E'Cindy HERBET'),
  (E'DESJARDINS CLEON', E'1522 route de tourville 76410 Cleon', NULL, E'Johann Monlouis'),
  (E'DESJARDINS MONTIVILLIERS', E'1 route des 4 saisons 76290 Montivilliers', NULL, E'Johann Monlouis'),
  (E'DESJARDINS TROUVILLE - ALLIQUERVILLE', NULL, NULL, E'Johann Monlouis'),
  (E'DUHAMEL LOGISTIQUE', E'Parc d''affaires des Portes Voie du Futur 27100 Val-de-Reuil', NULL, E'Cindy HERBET'),
  (E'EHPAD LE HAMEAU DE LA PELOU', NULL, NULL, E'Johann Monlouis'),
  (E'ELDEC FRANCE', NULL, NULL, E'Johann Monlouis'),
  (E'EMBALTEC', E'Voie du futur 27100 Val de Reuil', NULL, E'Cindy HERBET'),
  (E'ENTREPRISE AURILLACOISE TRAVAUX PUBLICS (EATP)', NULL, NULL, E'Johann Monlouis'),
  (E'ENTREPRISE CARCELLER', E'D86 81120 Realmont', NULL, E'Johann Monlouis'),
  (E'ENTREPRISE REY-BETBEDER', NULL, NULL, E'Johann Monlouis'),
  (E'EROME', NULL, NULL, E'Cindy HERBET'),
  (E'ESC PACK (CARTON SERVICE)', E'Rue de l orme au loup 45130 Baule', NULL, E'Cindy HERBET'),
  (E'ESPE SARL CHABANIS', NULL, NULL, E'Johann Monlouis'),
  (E'ESSEO', E'3 rue camille jenatzy 78260 Achères', NULL, E'Cindy HERBET'),
  (E'ETABLISSEMENT MONTALIER', E'18 Rue Sainte-Marie 33100 Bordeaux', NULL, E'Johann Monlouis'),
  (E'ÉTABLISSEMENTS DELAGREE - BRICOPRO ETRELLES', NULL, NULL, E'Johann Monlouis'),
  (E'ETPO - Entreprise de Travaux Publics de l''Ouest', E'467 route de la claie 49940 Noyant - Villages', NULL, E'Priscilla BEUZELIN'),
  (E'ETS BODIN-JOYEUX', NULL, NULL, E'Cindy HERBET'),
  (E'FARASSE FLUIDES', E'Rue du Champ de Tir Parc d''activités de Cantimpré 59400 Cambrai', NULL, E'Cindy HERBET'),
  (E'FBD INTERNATIONAL', E'71 rue de Provence 75009 Paris', NULL, E'Cindy HERBET'),
  (E'FLEFRO - MAGASIN 4 MURS', E'16 rue Antoine de st exupery 54710 FLEVILLE DEVANT NANCY', NULL, E'Johann Monlouis'),
  (E'FLEURS ET JARDINS POTIEZ - JARDINERIE POTIEZ', NULL, NULL, E'Johann Monlouis'),
  (E'FONDATION MALLET', NULL, NULL, E'Cindy HERBET'),
  (E'FORACO MANAGEMENT', NULL, NULL, E'Johann Monlouis'),
  (E'FOYER RURAL VETHEUIL', E'Place Jean Moulin 95510 Vetheuil', NULL, E'Cindy HERBET'),
  (E'FROFLE - MAGASIN IMAGINEA', E'9 rue Antoine de st exupery 54710 FLEVILLE DEVANT NANCY', NULL, E'Johann Monlouis'),
  (E'GENEVOIS FLEURS - VILLAVERDE MONTCEAU GOURDON', NULL, NULL, E'Johann Monlouis'),
  (E'GRAND DISTRIBUTION (CARREFOUR CONTACT)', NULL, NULL, E'Johann Monlouis'),
  (E'GRAND HÔTEL', NULL, NULL, E'Cindy HERBET'),
  (E'GROUPAMA PARIS VAL DE LOIRE', E'21 Rue des Boucheries 80600 Doullens', NULL, E'Cindy HERBET'),
  (E'GSM', E'Rue de l''Industrie 57970 Yutz', NULL, E'Johann Monlouis'),
  (E'HANDISERVICES', E'3-5 R Marcellin Berthelot Zone Artisanale De Parc Lann 56000 Vannes', NULL, E'Cindy HERBET'),
  (E'HANSGROHE', NULL, NULL, E'Cindy HERBET'),
  (E'HPB SPIE BATIGNOLLES', NULL, NULL, E'Johann Monlouis'),
  (E'IDRIS Centre National De La Recherche Scientifique CNRS', NULL, NULL, E'Cindy HERBET'),
  (E'IMMOBILIERE DES TECHNODES', NULL, NULL, E'Johann Monlouis'),
  (E'J2A - JARDINERIE DELBARD AUBEVOYE', NULL, NULL, E'Johann Monlouis'),
  (E'JARDI FREJUS - VILLAVERDE ROCCHIETTA FREJUS', NULL, NULL, E'Johann Monlouis'),
  (E'JARDI HYERES - VILLAVERDE ROCCHIETTA HYERES', NULL, NULL, E'Johann Monlouis'),
  (E'JARDI SAINT DOULCHARD - VILLAVERDE BOURGES - ST DOULCHARD', NULL, NULL, E'Johann Monlouis'),
  (E'JARDIFLEUR - VILLAVERDE BRETENIERE', NULL, NULL, E'Johann Monlouis'),
  (E'JARDILAND BREST GUIPAVAS', NULL, NULL, E'Johann Monlouis'),
  (E'JARDIMARNE - VILLAVERDE PIERRY', NULL, NULL, E'Johann Monlouis'),
  (E'JARDIN LOISIRS 28  ( GAMMVERT)', E'4 rue de l'''' Ormeteau 28300 Lèves', NULL, E'Johann Monlouis'),
  (E'JARDINERIE BONNEAU - VILLAVERDE NIORT', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE DE BROU - VILLAVERDE BOURG EN BRESSE', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE DES BREDANES - VILLAVERDE BAULE', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE DU BRIVADOIS - VILLAVERDE BRIOUDE', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE DU MOULIN - VILLAVERDE PIA', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE DUPOIRIER - LIBOURNE', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE GRANDEUR NATURE - VILLAVERDE TAVAUX', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE GUNTHER', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE LE GRAND VERT - VILLAVERDE ROCCHIETTA LE BEAUSSET', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE LES ORCHIS - VILLAVERDE AMBRONAY', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE SAUVEGRAIN - VILLAVERDE MONTARGIS - AMILLY', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE TARNAISE ALBI', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE TARNAISE FONLABOUR', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIE TARNAISE SUD CASTRES', NULL, NULL, E'Johann Monlouis'),
  (E'JARDINERIES ET PAYSAGES - VILLAVERDE ANTIBES', NULL, NULL, E'Johann Monlouis'),
  (E'JUNGLE PRESTATIONS', NULL, NULL, E'Johann Monlouis'),
  (E'KOM - O BRICO LA MONTAGNE', NULL, NULL, E'Johann Monlouis'),
  (E'LA FABRIQUE', E'77 Allée des Carrières 93150 Le Blanc-Mesnil', NULL, E'Cindy HERBET'),
  (E'LAIGNEL', E'3 ROUTE NATIONALE 62138 AUCHY-LES-MINES', NULL, E'Cindy HERBET'),
  (E'LARREY&CO', NULL, NULL, E'Johann Monlouis'),
  (E'LE FIVE - TRIBAL FOOT', E'route de torcy 77360 Vaires-sur-Marne', E'361 avenue du président Wilson 93210 Saint Denis', E'Cindy HERBET'),
  (E'LE FIVE NANCY', NULL, NULL, E'Johann Monlouis'),
  (E'LE FIVE OL', NULL, NULL, E'Johann Monlouis'),
  (E'LE LUCERNAIRE FORUM', NULL, NULL, E'Johann Monlouis'),
  (E'LES COURANTS ET CIE', NULL, NULL, E'Cindy HERBET'),
  (E'LES JARDINERIES DU SALEVE ASL - FLEURS ET PLANTES DU LAC ANT', NULL, NULL, E'Johann Monlouis'),
  (E'LES JARDINS DE PETRUS - VILLAVERDE BRIVE-LA-GAILLARDE', NULL, NULL, E'Johann Monlouis'),
  (E'LES JARDINS DU FAUCIGNY - VILLAVERDE ST PIERRE EN FAUCIGNY', NULL, NULL, E'Johann Monlouis'),
  (E'LES JARDINS DU VIDOURLE - VILLAVERDE LUNEL', NULL, NULL, E'Johann Monlouis'),
  (E'LES NOUVEAUX CONSTRUCTEURS (LNC)', NULL, NULL, E'Cindy HERBET'),
  (E'LES PEP DU CENTRE DE LA BOURGOGNE FRANCHE COMTE (CBFC)', NULL, NULL, E'Cindy HERBET'),
  (E'LG - JARDINERIE ROCCHIETTA - VILLAVERDE  LA GARDE', NULL, NULL, E'Johann Monlouis'),
  (E'LPO LYCEE DES METIERS HENRI POINCARE', NULL, NULL, E'Cindy HERBET'),
  (E'Mairie de Bonnières sur Seine', E'hall du marché, église 45 rue Georges Herrewyn 78270 Bonnières-sur-Seine', NULL, E'Cindy HERBET'),
  (E'MAIRIE DE CRAVENT', E'36 Rue Magloire Douville 78270 Cravent', NULL, E'Cindy HERBET'),
  (E'Mairie de Giroux', E'Étang des frênes 36150 Giroux', NULL, E'Cindy HERBET'),
  (E'Mairie de GUILLY', NULL, NULL, E'Cindy HERBET'),
  (E'Mairie de LIZERAY', NULL, NULL, E'Cindy HERBET'),
  (E'Mairie de MENETREOLS SOUS VATAN', NULL, NULL, E'Cindy HERBET'),
  (E'Mairie de Mézières-sur-Seine', E'Place du Commandant Grimblot, Rue Maurice Fricotte 78970 Mézières-sur-Seine', E'Place du commandant grimblot 78970 Mézières sur Seine', E'Cindy HERBET'),
  (E'Mairie de Reboursin Le Bourg', NULL, NULL, E'Cindy HERBET'),
  (E'Mairie de Saint Aubin', NULL, NULL, E'Cindy HERBET'),
  (E'MAIRIE DE VERNEUIL SUR SEINE', E'1 Place de la Galette 78480 Verneuil-sur-Seine', NULL, E'Johann Monlouis'),
  (E'Mairie Saint Pierre de Jards', NULL, NULL, E'Cindy HERBET'),
  (E'MAISON FRANCOIS CHOLAT (G.A.I.C.)', E'Roche plage 1310 route de thuile 38510 Morestel', NULL, E'Johann Monlouis'),
  (E'MANUFACTURE DE SENLIS', NULL, NULL, E'Johann Monlouis'),
  (E'MASSIMO DUTTI FRANCE', E'Rue royale, place de la Madeleine 75008 PARIS', NULL, E'Cindy HERBET'),
  (E'MB MANAGEMENT - LA GALLERIE ART DE NUIT', NULL, NULL, E'Johann Monlouis'),
  (E'MECANIQUE TOLERIE SERRURERIE (MTS)', NULL, NULL, E'Cindy HERBET'),
  (E'MEDECINS DU MONDE', E'33 rue fouret 44000 Nantes', NULL, E'Cindy HERBET'),
  (E'MEONI MATERIAUX - BIGMAT ET LA BRIQUETERIE', E'Ancien meoni morta 20243 Prunelli di fiumorbo', NULL, E'Johann Monlouis'),
  (E'MIRAHBEL - LA TERRE QUI CHANTE', NULL, NULL, E'Johann Monlouis'),
  (E'MONT D''ARBOIS LUXURY RESORT (MALR)', E'33/63 Route des crêtes 74170 Saint Gervais les bains', NULL, E'Johann Monlouis'),
  (E'MONTBARD JARDIN - VILLAVERDE FAIN LES MONTBARD', NULL, NULL, E'Johann Monlouis'),
  (E'MOURIER PARTICIPATION 3MMM', E'Impasse d''''Angouleme 16230 Maine de boixe', NULL, E'Johann Monlouis'),
  (E'NewCold Argentan SAS', NULL, NULL, E'Cindy HERBET'),
  (E'N''PACK - intégré au client DUHAMEL', NULL, NULL, E'Cindy HERBET'),
  (E'OFFICE PUBLIC HABITAT DU CHER - VAL DE BERRY', NULL, NULL, E'Johann Monlouis'),
  (E'OGEC F. CABRINI', NULL, NULL, E'Cindy HERBET'),
  (E'ORCA DISTRIBUTION', E'Parc d''''activité des ajeux  Rue Pierre Gilles de Genne 72400 La Ferté-Bernard', NULL, E'Cindy HERBET'),
  (E'ORVIA - COUVOIR DE LA MESANGERE LA POITEVINIERE', NULL, NULL, E'Johann Monlouis'),
  (E'OUTAREX', E'156 rue du Grand But 59160 LILLE', NULL, E'Cindy HERBET'),
  (E'PAPREC GRAND ILE DE FRANCE AGENCE TRIVALORISATION', E'16-24 route de la seine 92230 Gennevilliers', NULL, E'Cindy HERBET'),
  (E'PARC HÔTEL', NULL, NULL, E'Cindy HERBET'),
  (E'PEPINIERE MERCIER- VILLAVERDE DIJON - ASNIÈRES-LES-DIJON', NULL, NULL, E'Johann Monlouis'),
  (E'PHARMACIE DE LA PAIX', NULL, NULL, E'Cindy HERBET'),
  (E'PILKINGTON AUTOMOTIVE FRANCE', E'12 Boulevard des Martyrs de Châteaubriant 95100 Argenteuil', NULL, E'Cindy HERBET'),
  (E'PORT GRIMAUD GARDEN CENTER - VILLAVERDE ROCCHIETTA GRIMAUD', NULL, NULL, E'Johann Monlouis'),
  (E'PULL & BEAR FRANCE', E'90 rue d Antibes 06400 Cannes', NULL, E'Johann Monlouis'),
  (E'PYLONES', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'RE TRAVAUX PUBLICS (RE TP)', E'18 rue 11 novembre 17740 Sainte-Marie-de-Ré', NULL, E'Cindy HERBET'),
  (E'RM-JARDINERIE ROCHIETTA–VILLAVERDE AIX EN PROVENCE MEYREUIL', NULL, NULL, E'Johann Monlouis'),
  (E'SA ENTREPRISE GREGORY (EMG)', E'Gours 46270 Cuzac', NULL, E'Johann Monlouis'),
  (E'SABLIERES ET CARRIERES DE LA MADELEINE', E'46270 Cuzac', NULL, E'Johann Monlouis'),
  (E'SAINT VIT MATERIAUX - BIGMAT', NULL, NULL, E'Johann Monlouis'),
  (E'SARL ATHLETIC FORME', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'SAS SOCIETE EXPLOITATION LLM - MERCURE', NULL, NULL, E'Cindy HERBET'),
  (E'SAS VOLTA', E'2 Rue Vincent Van Gogh 76290 Montivilliers', NULL, E'Cindy HERBET'),
  (E'SAUVEGARDE FORMATION', E'11 Rue du Moulin À Poudre 76150 Maromme', NULL, E'Cindy HERBET'),
  (E'SCI BOUCHAYER C/O ARTENA', E'10 rue de l Arménie 38000 Grenoble', NULL, E'Johann Monlouis'),
  (E'SCM DENTAIRE D''OSNY SEL SYMCHOWICZ', NULL, NULL, E'Cindy HERBET'),
  (E'SEQENS SOCIETE ANONYME D''HABITATIONS A LOYER MODERE', E'2-12 Parvis Colonel Arnaud Beltrame 78000 Versailles', NULL, E'Cindy HERBET'),
  (E'SIARP', E'58 Rue Gioacchino Rossini 95310 Saint-Ouen-l''Aumône', NULL, E'Cindy HERBET'),
  (E'SICOREN', E'2 avenue de la gare 78980 Breval', NULL, E'Cindy HERBET'),
  (E'SOC EXPLOIT DES ETS CHARRIER - MASTERPRO CHARRIER LA CHATRE', E'7 rue mirebeaux 36400 La chatre', NULL, E'Johann Monlouis'),
  (E'SOC INSTALL TELEPHON SIGNALISATION (SITS)', NULL, NULL, E'Cindy HERBET'),
  (E'SOCIETE DES ETABLISSEMENTS MAISONNIER', E'32 avenue de bel air 86150 L''''ISLE JOURDAIN', NULL, E'Johann Monlouis'),
  (E'SOCIETE D''EXPLOITATION ET DE DETENTION HOTELIERE VISTA', E'52 Avenue Sir Winston Churchill 06190 Roquebrune-Cap-Martin', NULL, E'Johann Monlouis'),
  (E'SOCIETE EXPLOITATION TERRE ET MONTAGNE ( group moma)', E'3461 route de la côte 2000 74120 Megeve', NULL, E'Johann Monlouis'),
  (E'SOCIETE HOTELIERE AVENUE BOLLEE - KYRIAD LE MANS EST', NULL, NULL, E'Cindy HERBET'),
  (E'SOCIETE NOUVELLE DEGUIL', NULL, NULL, E'Cindy HERBET'),
  (E'SOGECER EQUIPEMENT ROUTIER', E'22 Chemin d''Auguste 33610 Cestas', NULL, E'Johann Monlouis'),
  (E'SOLUTION SECURITE INCENDIE', NULL, NULL, E'Priscilla BEUZELIN'),
  (E'SPIE BATIGNOLLES', E'34 Rue Benoît Frachon 94500 Champigny-sur-Marne', NULL, E'Cindy HERBET'),
  (E'SPIE BATIGNOLLES BLONDET', NULL, NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES ENERGIE', E'300 Rue de Lille Parc Tertiaire Rivéo I, Batiment A, RDC 59520 MARQUETTE LEZ LILLE', NULL, E'Cindy HERBET'),
  (E'SPIE BATIGNOLLES ENERGIE - SOUCHON (SBE - SOUCHON)', E'12 Rue de l''Europe 31150 Lespinasse', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES ENERGIE GRAND SUD', E'222 Chemin de la Pertuade 83140 Six-Fours-les-Plages', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES GENIE CIVIL', E'60 avenue d Aquitaine 33380 MARCHEPRIME', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES GRAND OUEST', E'Rue André Marie ampère 33127 Saint-Jean-d''Illac', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES ILE-DE-FRANCE (SCGPM)', E'55 Chemin de le huniere 91120 Palaiseau', E'113 Avenue Aristide Briand 94743 Accueil cedex', E'Cindy HERBET'),
  (E'SPIE BATIGNOLLES MALET', E'98 route de Cambarras 83440 Tourrettes', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES NORD', E'224 Avenue de la Dordogne 59140 Dunkerque', NULL, E'Cindy HERBET'),
  (E'SPIE BATIGNOLLES PRESANCE IDF', E'Rue des vignes 77990 Le Mesnil Amelot', NULL, E'Cindy HERBET'),
  (E'SPIE BATIGNOLLES SUD EST', E'Carrefour du caban D268 13270 Fos sur mer', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES TP AURA', E'Lieu dit Fontaine 38510 Arandon', NULL, E'Johann Monlouis'),
  (E'SPIE BATIGNOLLES VALERIAN', E'EOLE-Triangles de Mantes Impasse Sainte-Claire Déville 78200 Mantes-la-Jolie', NULL, E'Cindy HERBET'),
  (E'STELO FORMATION', E'13 rue des halles 71150 Chagny', NULL, E'Johann Monlouis'),
  (E'STRADIVARIUS FRANCE', E'Promenade Sainte-Catherine 33000 Bordeaux', NULL, E'Johann Monlouis'),
  (E'SYXPERIANE', E'3 Mail du Front populaire 44200 Nantes', NULL, E'Cindy HERBET'),
  (E'TARN ENROBES', E'Route d''''aridité 81120 Terre de bancalie', NULL, E'Johann Monlouis'),
  (E'TPF INVEST', NULL, NULL, E'Cindy HERBET'),
  (E'TRANSPORTS RABOUIN SAS', E'Chemin des ânes 91790 Boissy sous saint yon', NULL, E'Johann Monlouis'),
  (E'TRANSURBAIN EVREUX (TRANSURBAIN SPL)', E'1 Rue Jean Jaurès 27000 Évreux', NULL, E'Cindy HERBET'),
  (E'VASSE TRANSFERT', NULL, NULL, E'Cindy HERBET'),
  (E'VILLAVERDE LA JARDINERIE D''AVALLON', NULL, NULL, E'Johann Monlouis'),
  (E'WEISS - GEDIMAT - BRICO PRO WEISS', NULL, NULL, E'Johann Monlouis'),
  (E'YACHT SOLUTIONS', E'179 quai de brazza 33100 Bordeaux', NULL, E'Cindy HERBET'),
  (E'ZARA FRANCE', E'Place de la madeleine 75008 Paris', NULL, E'Cindy HERBET'),
  (E'ZARA HOME FRANCE', E'1 bis place masséna 06000 Nice', NULL, E'Johann Monlouis'),
  (E'ZARA MONACO SAM', E'Zara Avenue de l''Hermitage 98000 Monaco', NULL, E'Johann Monlouis')
ON CONFLICT (nom) DO NOTHING;

-- ── 7. Vue facturation ───────────────────────────────────────────────
CREATE OR REPLACE VIEW public.v_clients_facturation AS
SELECT
  c.id, c.nom, c.commercial, c.email_facturation, c.siret,
  c.tarif_contrat, c.type_contrat,
  COUNT(i.id) AS nb_interventions,
  COUNT(i.id) FILTER (WHERE i.date >= date_trunc('year', NOW())) AS interventions_annee,
  MAX(i.date) AS derniere_intervention,
  c.actif, c.notes_facturation
FROM public.clients c
LEFT JOIN public.interventions i ON i.client = c.nom
GROUP BY c.id, c.nom, c.commercial, c.email_facturation, c.siret,
         c.tarif_contrat, c.type_contrat, c.actif, c.notes_facturation
ORDER BY c.nom;

-- ── Résultat ─────────────────────────────────────────────────────────
SELECT 'OK — ' || COUNT(*) || ' clients insérés' AS resultat FROM public.clients;